version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suporter-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:8080"
    networks:
      - tirenn-net

networks:
  tirenn-net:
    external: true
