version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: suporter-backend
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
